### ISSUE TITLE
Bug when swapping all runes, they appear as a card

### ISSUE THREAD

**Issue by Zamiell** [TazTxUK/MinimapAPI#16]
It shows up as a card on the minimap for about a second, then it switches back to a rune

**Comment by Zamiell** [comment]
actually seems to happen with all runes

**Comment by TazTxUK** [comment]
Can't recreate this bug. Perhaps it was fixed in an earlier commit

**Comment by Zamiell** [comment]
Still happens on master.
Steps to reproduce:
1) Set the map to large mode.
2) Set the minimap option to show pickups in the current room to true.
3) `g k35`
4) `g k36`
5) Touch the rune on the ground and look at the minimap.

**Comment by TazTxUK** [comment]
Fixed in commit 00db34e21d71d468bf57f7cbff96091562db4dc2
